/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QuizEs {
        "countEdges": boolean;
        "nextText": string;
        "questionsKey": string;
        "startText": string;
    }
    interface QuizEsProgress {
        "countEdges": boolean;
        "step": number;
        "steps": number;
    }
    interface QuizEsQuestion {
        "choices": string[];
        "currentStep": number;
        "nextText": string;
        "question": string;
        "step": number;
    }
    interface QuizEsStep {
        "currentStep": number;
        "step": number;
        "type": string;
    }
}
declare global {
    interface HTMLQuizEsElement extends Components.QuizEs, HTMLStencilElement {
    }
    var HTMLQuizEsElement: {
        prototype: HTMLQuizEsElement;
        new (): HTMLQuizEsElement;
    };
    interface HTMLQuizEsProgressElement extends Components.QuizEsProgress, HTMLStencilElement {
    }
    var HTMLQuizEsProgressElement: {
        prototype: HTMLQuizEsProgressElement;
        new (): HTMLQuizEsProgressElement;
    };
    interface HTMLQuizEsQuestionElement extends Components.QuizEsQuestion, HTMLStencilElement {
    }
    var HTMLQuizEsQuestionElement: {
        prototype: HTMLQuizEsQuestionElement;
        new (): HTMLQuizEsQuestionElement;
    };
    interface HTMLQuizEsStepElement extends Components.QuizEsStep, HTMLStencilElement {
    }
    var HTMLQuizEsStepElement: {
        prototype: HTMLQuizEsStepElement;
        new (): HTMLQuizEsStepElement;
    };
    interface HTMLElementTagNameMap {
        "quiz-es": HTMLQuizEsElement;
        "quiz-es-progress": HTMLQuizEsProgressElement;
        "quiz-es-question": HTMLQuizEsQuestionElement;
        "quiz-es-step": HTMLQuizEsStepElement;
    }
}
declare namespace LocalJSX {
    interface QuizEs {
        "countEdges"?: boolean;
        "nextText"?: string;
        "onQuizCompleted"?: (event: CustomEvent<any>) => void;
        "questionsKey"?: string;
        "startText"?: string;
    }
    interface QuizEsProgress {
        "countEdges"?: boolean;
        "step"?: number;
        "steps"?: number;
    }
    interface QuizEsQuestion {
        "choices"?: string[];
        "currentStep"?: number;
        "nextText"?: string;
        "onQuestionCompleted"?: (event: CustomEvent<any>) => void;
        "question"?: string;
        "step"?: number;
    }
    interface QuizEsStep {
        "currentStep"?: number;
        "step"?: number;
        "type"?: string;
    }
    interface IntrinsicElements {
        "quiz-es": QuizEs;
        "quiz-es-progress": QuizEsProgress;
        "quiz-es-question": QuizEsQuestion;
        "quiz-es-step": QuizEsStep;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "quiz-es": LocalJSX.QuizEs & JSXBase.HTMLAttributes<HTMLQuizEsElement>;
            "quiz-es-progress": LocalJSX.QuizEsProgress & JSXBase.HTMLAttributes<HTMLQuizEsProgressElement>;
            "quiz-es-question": LocalJSX.QuizEsQuestion & JSXBase.HTMLAttributes<HTMLQuizEsQuestionElement>;
            "quiz-es-step": LocalJSX.QuizEsStep & JSXBase.HTMLAttributes<HTMLQuizEsStepElement>;
        }
    }
}
